site_name: My Docs
site_url: https://mattscy.github.io/MagicAPI
repo_name: mattscy/MagicAPI
repo_url: https://github.com/mattscy/MagicAPI

theme:
  name: material


nav:
  - Home: index.md
  - API:
    - Magic: api/magic/
    - Object: api/object/
    - Subscription: api/subscription/
    - HitDetails: api/hitdetails/
  - Articles:
    - Priority of Forces: articles/forcepriorities/


markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences